#!/usr/bin/env python3

import http.client
import urllib.parse
import io
import sys
import os

URL = "p.nikitapek.in"
PORT = "80"

data_reader = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
lines = ''.join(data_reader.readlines())
data = urllib.parse.urlencode({'data': lines})
headers = {"Content-type": "application/x-www-form-urlencoded", "Accept": "text/plain"}

try:
    conn = http.client.HTTPConnection(URL, PORT)
    conn.request("POST", "/", data, headers)
    response = conn.getresponse()
    conn.close()

    print(response.getheader('Location'))
except:
    pass
